version: "3"
services:
  api:
    build: ./api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=http://johnmogi.com
      - MONGO_URL="mongodb://api_db:27017/api"
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:latest
